# Numpy
numpy란 python에서 데이터 과학 및 데이터 분석에 도움을 주는 패키지 입니다  
다차원 배열 데이터, 행렬 계산을 훨씬 효과적으로 계산할 수 있습니다!

In [1]:
#먼저 numpy를 설치 후 불러옵니다
!pip install numpy
import numpy as np # 관례적으로 줄여서 np로 사용합니다( as는 모듈의 별명을 지정합니다)

## 1. 넘파이 배열 생성
np.array: 인자로 itterable한 객체를 받고 넘파이의 array형식으로 반환합니다

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
# 다양한 array생성
import random
arr1=np.array(range(10))
arr2=np.array([random.uniform(-1,1) for i in range(10)])

print('arr1:',arr1)
print('arr2:',arr2)

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2: [ 0.15110129  0.57577258  0.3785035   0.20038896 -0.97131914 -0.36293076
  0.41514065 -0.13193545 -0.62203862 -0.17843147]


넘파이 배열은 요소의 모든 데이터 타입이 동일하게 됩니다!  
nd.dtype은 넘파이 배열의 데이터 타입을 반환합니다

In [4]:
arr3=np.array([1,-2,0.3,4,2]) # 나머지 int형 요소도 float형으로 변경된 것을 확인할 수 있습니다!
arr4=np.array([1,'2','a','b',{1,2,3},2.0,32.4])

print('arr3:',arr3,arr3.dtype)
print('arr4:',arr4,arr4.dtype)

arr3: [ 1.  -2.   0.3  4.   2. ] float64
arr4: [1 '2' 'a' 'b' {1, 2, 3} 2.0 32.4] object


In [5]:
# nd.shape 넘파이 배열의 형태를 반환합니다
arr5=np.array([[1,2,3],
                [4,5,6]])

arr6=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr5.shape)
print(arr6.shape)

(2, 3)
(1, 3, 3)


In [6]:
#np.ndim: 넘파이 배열의 차원 수를 반환합니다
arr=np.array([range(10),
            range(10,20),
            range(20,30)])
            
print('arr는 %d차원 배열입니다'%(arr.ndim))

arr는 2차원 배열입니다


In [7]:
# np.arange: 파이썬의 arange와 사용방법이 같으며 넘파이 배열을 반환합니다
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
# np.linspace(start, end, num=50, endpoint=True): num개의 동일한 편차를 갖는 배열을 반환합니다 (endpoint는 마지막 값에 end를 포함할 지 여부입니다)
print(np.linspace(0,100,11,endpoint=True))
print(np.linspace(5,63,12))
print(np.linspace(50,100,endpoint=False))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 5.         10.27272727 15.54545455 20.81818182 26.09090909 31.36363636
 36.63636364 41.90909091 47.18181818 52.45454545 57.72727273 63.        ]
[50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67.
 68. 69. 70. 71. 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85.
 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [9]:
# np.random.rand(d,d1,d2...): 0과 1사이의 난수를 생성하며 인자의 수 만큼의 차원을 가진 배열을 생성합니다
np.random.rand(1,1,5)

array([[[0.6607953 , 0.95708742, 0.18723084, 0.05072498, 0.58101578]]])

In [10]:
# np.random.randint(low,high,size): low와 high-1사이의 수 중에서 size 형태의 넘파이 배열을 생성합니다 
np.random.randint(1,10,(2,5))

array([[8, 2, 2, 3, 1],
       [2, 2, 8, 3, 4]])

In [11]:
# np.random.randn(d,d1,d2...): 평균이 0 표준편차가 1인 전규분포에서 인자의 수 만큼의 차원을 가진 배열을 생성합니다
np.random.randn(10)

array([ 1.09709471, -0.91579154,  3.19544298, -0.34059103,  1.32013411,
       -0.74390375,  1.81488091, -0.92427946,  2.39127569,  0.46099738])

## 2. 넘파이 배열 형태변경
shape함수로 넘파이 배열의 형태를 변경할 수 있습니다

In [12]:
# 새로운 배열 생성
even_number=np.arange(2,21,2)
print('변경 전:',even_number.shape)
even_number.shape=(2,5)
print('변경 후:\n', even_number, even_number.shape)

변경 전: (10,)
변경 후:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]] (2, 5)


In [13]:
# reshape(): ndarray의 차원과 크기를 변경합니다.

array_ex1 = np.arange(10)
print('array_ex1:\n', array_ex1)

# 쉽게 10 개의 값을 5개씩 2세트로 이해
array_ex2 = array_ex1.reshape(2, 5)
print('\narray_ex2:\n', array_ex2)
# 쉽게 10 개의 값을 2개씩 5세트로 이해
array_ex3 = array_ex1.reshape(5, 2)
print('\narray_ex3:\n', array_ex3)

# 만약 array_ex1.reshape(4, 2)처럼 변경이 불가능하면 오류를 발생시킵니다.

# -1은 알아서 호환되는 값으로 변경되어 ndarray로 만들어줍니다.
array_ex4 = array_ex1.reshape(-1, 5)
print('\narray_ex4:\n', array_ex4)
print('--->',array_ex4.shape, '\n여기서 -1이 2로 변경')
array_ex5 = array_ex1.reshape(2, -1)
print('\narray_ex5:\n', array_ex5)
print('--->',array_ex5.shape, '\n여기서 -1이 5로 변경')

# 마찬가지로 array_ex1.reshape(4, -1)처럼 변경이 불가능하면 오류를 발생시킵니다.

array_ex1:
 [0 1 2 3 4 5 6 7 8 9]

array_ex2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array_ex3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

array_ex4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
---> (2, 5) 
여기서 -1이 2로 변경

array_ex5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
---> (2, 5) 
여기서 -1이 5로 변경


shape를 통한 배열 변경은 원본 배열을 변경시키지만  
reshape는 변경 배열을 반환만 합니다

In [14]:
# nd.astype(dtype): 넘파이 배열의 데이터 타입을 변경합니다
arr=np.array([1.2,1,-0.2])
arr.astype('object')

array([1.2, 1.0, -0.2], dtype=object)

In [15]:
# np.zeros(size), np.ones(size): size 형태의 모두 0으로 된(1로 된)넘파이 배열을 생성합니다
print(np.zeros((2,5)))
print(np.ones((1,3,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
# np.sort(), ndarray.sort()함수: 행렬을 정리하는 함수입니다.
org_array = np.array([3, 1, 8, 4])
print('원본 행렬:', org_array)
print()

# np.sort()함수를 사용하면 원래의 행렬은 그대로 유지한 채 정렬합니다
print(np.sort(org_array))
print('org_array가 바뀌지 않았습니다:',org_array)
print()

# ndarray.sort()함수를 사용하면 원래의 행렬을 정렬합니다.
print(org_array.sort())
print('org_array가 바뀌었습니다:',org_array)
print()

# 내림차순으로 정렬하기 위해서는 [::-1]을 적용하면 됩니다.
down_array = np.sort(org_array)[::-1]
print('내림차순으로 정렬되었습니다:',down_array)

원본 행렬: [3 1 8 4]

[1 3 4 8]
org_array가 바뀌지 않았습니다: [3 1 8 4]

None
org_array가 바뀌었습니다: [1 3 4 8]

내림차순으로 정렬되었습니다: [8 4 3 1]


## 3. 넘파이 배열 인덱싱

In [17]:
# np.nan: not of number(null값), np.inf: infinity(무한)
arr=np.array([np.nan, np.inf, 20,-30.])
arr[0:2]

array([nan, inf])

In [18]:
#-> ndarray에 해당하는 위치의 인덱스 값을 []안에 입력
# 3(0부터 시작이기 때문에 2)번째 값 추출
print(array_ex1[2])
print()

# array_ex1의 값을 수정할 수 있습니다. (첫 번째 값을 1로 바꾸기)
array_ex1[0]=8
print(array_ex1)
print()
array_ex1[0]=0

# 2차원의 ndarray의 경우 [row위치, column위치]로 로우와 칼럼의 위치 인덱스를 통해 접근이 가능합니다.
print(array_ex3)
print('(row=1, col=0) index 가리키는 값: ',array_ex3[1, 0])
print('(row=3, col=1) index 가리키는 값: ',array_ex3[3, 1])
print('(row=4, col=1) index 가리키는 값: ',array_ex3[4, 1])
print()

# ':'(콜론)을 이용하여 선택
zero_to_one = array_ex1[:2]
print(zero_to_one)
one_to = array_ex1[1:]
print(one_to)
print()

# 마찬가지로 2차원의 ndarray의 경우 [row위치, column위치]로 로우와 칼럼의 위치 인덱스를 통해 접근이 가능합니다.
print(array_ex3)
print('(row=1~2, col=0~1) index 가리키는 값: \n', array_ex3[1:3, 0:2])

2

[8 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(row=1, col=0) index 가리키는 값:  2
(row=3, col=1) index 가리키는 값:  7
(row=4, col=1) index 가리키는 값:  9

[0 1]
[1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(row=1~2, col=0~1) index 가리키는 값: 
 [[2 3]
 [4 5]]


## 4. 넘파이 배열 연산

In [19]:
# 배열의 사칙연산
arr=np.arange(4).reshape(2,2)
print(arr+3,'\n')
print(arr-3,'\n')
print(arr*10,'\n')
print(arr/10)

[[3 4]
 [5 6]] 

[[-3 -2]
 [-1  0]] 

[[ 0 10]
 [20 30]] 

[[0.  0.1]
 [0.2 0.3]]


In [20]:
# 배열의 합, 평균, 분산, 표준편차
print(arr.sum(),'\n')
print(arr.mean(),'\n')
print(arr.var(),'\n')
print(arr.std())

6 

1.5 

1.25 

1.118033988749895


In [21]:
# 배열의 최소, 최대, 누적합, 누적곱
print(arr.min(),'\n')
print(arr.max(),'\n')
print(arr.cumsum(),'\n')
print(arr.cumprod())

0 

3 

[0 1 3 6] 

[0 0 0 0]


## 5. 넘파이 행렬연산 

In [22]:
# 행렬곱
matrix_1=np.array([[1,90],
                    [2,63]])

matrix_2=np.array([[3,87],
                    [4,30]])

## 모두 행렬곱을 의미
matrix_1.dot(matrix_2)
matrix_1@matrix_2
np.matmul(matrix_1, matrix_2)

array([[ 363, 2787],
       [ 258, 2064]])

In [23]:
# 전치행렬
matrix=np.array([[1,2],
                [4,5],
                [7,8]])

## 모두 전치행렬을 의미
matrix.T
matrix.transpose()
np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8]])

In [24]:
# 역행렬
matrix_1i=np.linalg.inv(matrix_1)
print(matrix_1i,'\n')
# e-17은 10의 -17제곱 이므로 거의 0에 가깝습니다
print(matrix_1@matrix_1i)

[[-0.53846154  0.76923077]
 [ 0.01709402 -0.00854701]] 

[[ 1.00000000e+00 -3.46944695e-17]
 [-6.24500451e-17  1.00000000e+00]]
